import React,{useEffect,useMemo,useState} from 'react';
import {BookOpen,Image,LayoutTemplate,FileCheck2,Download,Upload,Plus,Sparkles,LogOut,Save,FolderOpen,ArrowLeft,Clock3,Trash2} from 'lucide-react';
import {supabase} from './lib/supabase';

const steps=[['Conteúdo',BookOpen],['Estilo',Sparkles],['Imagens',Image],['Diagramar',LayoutTemplate],['Revisar',FileCheck2],['Exportar',Download]];
const assetTypes=[['cover','Capa'],['back_cover','Contracapa'],['internal','Ilustração interna'],['mockup','Mockup 3D']];
const clean=v=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'-');
const parse=v=>{try{return v?JSON.parse(v):{}}catch{return{}}};
const date=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
const chunkText=(text,size=1800)=>{const parts=[];let buf='';for(const p of text.split(/\n+/).map(x=>x.trim()).filter(Boolean)){if((buf+' '+p).length>size&&buf){parts.push(buf.trim());buf=p}else buf+=(buf?'\n\n':'')+p}if(buf.trim())parts.push(buf.trim());return parts.length?parts:['Conteúdo sem texto extraível.']};

function Auth(){const[mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setMsg('');const r=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)setMsg(r.error.message);else if(mode==='signup'&&!r.data.session)setMsg('Conta criada. Confirme o e-mail para entrar.');setBusy(false)};return <div className="authShell"><form className="authCard" onSubmit={submit}><div className="logo authLogo">E</div><h1>Ebook Studio IA</h1><p>Entre para salvar seus projetos e arquivos.</p><label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary full" disabled={busy}>{busy?'Aguarde...':mode==='login'?'ENTRAR':'CRIAR CONTA'}</button><button type="button" className="linkBtn" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Ainda não tenho conta':'Já tenho conta'}</button>{msg&&<div className="notice">{msg}</div>}</form></div>}

export default function App(){
 const[session,setSession]=useState(null),[ready,setReady]=useState(false),[view,setView]=useState('dashboard'),[projects,setProjects]=useState([]),[loadingProjects,setLoadingProjects]=useState(false),[step,setStep]=useState(0),[project,setProject]=useState(null),[ebook,setEbook]=useState(null),[file,setFile]=useState(null),[name,setName]=useState(''),[format,setFormat]=useState('A5_vertical'),[language,setLanguage]=useState('pt-BR'),[audience,setAudience]=useState('Família'),[visualStyle,setVisualStyle]=useState('3D Premium'),[assets,setAssets]=useState([]),[assetUrls,setAssetUrls]=useState({}),[assetPrompt,setAssetPrompt]=useState(''),[pages,setPages]=useState([]),[selectedPage,setSelectedPage]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)});const{data:s}=supabase.auth.onAuthStateChange((_e,n)=>setSession(n));return()=>s.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadProjects()},[session]);
 useEffect(()=>{if(project?.id&&step>=2)loadAssets(project.id);if(ebook?.id&&step>=3)loadPages(ebook.id)},[project?.id,ebook?.id,step]);
 const title=useMemo(()=>steps[step][0],[step]);
 const loadProjects=async()=>{setLoadingProjects(true);const{data}=await supabase.from('projects').select('*,ebooks(id,title,source_file_path,source_type,content_status,updated_at)').order('updated_at',{ascending:false});setProjects(data||[]);setLoadingProjects(false)};
 const loadAssets=async id=>{const{data,error}=await supabase.from('assets').select('*').eq('project_id',id).order('created_at',{ascending:false});if(error)return setNotice(`Erro: ${error.message}`);setAssets(data||[]);const urls={};for(const a of data||[]){const{data:s}=await supabase.storage.from('ebook-assets').createSignedUrl(a.file_path,3600);if(s?.signedUrl)urls[a.id]=s.signedUrl}setAssetUrls(urls)};
 const loadPages=async id=>{const{data}=await supabase.from('pages').select('*').eq('ebook_id',id).order('sort_order',{ascending:true});setPages(data||[]);if(data?.length&&!selectedPage)setSelectedPage(data[0])};
 if(!ready)return <div className="loading">Carregando Ebook Studio IA...</div>;if(!session)return <Auth/>;
 const reset=()=>{setProject(null);setEbook(null);setFile(null);setName('');setFormat('A5_vertical');setLanguage('pt-BR');setAudience('Família');setVisualStyle('3D Premium');setAssets([]);setPages([]);setSelectedPage(null);setStep(0);setView('editor');setNotice('Novo projeto iniciado.')};
 const open=item=>{const s=parse(item.style_notes);setProject(item);setEbook(item.ebooks?.[0]||null);setName(item.name||'');setFormat(item.format||'A5_vertical');setLanguage(item.language||'pt-BR');setAudience(s.audience||'Família');setVisualStyle(s.visualStyle||'3D Premium');setStep(Math.max(0,Math.min(5,item.current_step||0)));setView('editor');setNotice('Projeto carregado.')};
 const goto=async n=>{setStep(n);if(project){await supabase.from('projects').update({current_step:n}).eq('id',project.id);setProject(p=>({...p,current_step:n}))}};
 const saveContent=async()=>{if(!name.trim())return setNotice('Digite o nome do projeto.');if(!file&&!ebook?.source_file_path)return setNotice('Selecione um PDF ou DOCX.');setBusy(true);try{let p=project;if(!p){const r=await supabase.from('projects').insert({user_id:session.user.id,name:name.trim(),format,language,current_step:1,style_notes:JSON.stringify({audience,visualStyle})}).select().single();if(r.error)throw r.error;p=r.data;setProject(p)}else{const r=await supabase.from('projects').update({name:name.trim(),format,language,current_step:1,style_notes:JSON.stringify({audience,visualStyle})}).eq('id',p.id).select().single();if(r.error)throw r.error;p=r.data;setProject(p)}let path=ebook?.source_file_path||null,type=ebook?.source_type||null;if(file){path=`${session.user.id}/${p.id}/${Date.now()}-${clean(file.name)}`;type=file.name.split('.').pop()?.toLowerCase();const u=await supabase.storage.from('ebook-sources').upload(path,file,{contentType:file.type||undefined});if(u.error)throw u.error}let e=ebook;if(!e){const r=await supabase.from('ebooks').insert({project_id:p.id,title:name.trim(),source_file_path:path,source_type:type}).select().single();if(r.error)throw r.error;e=r.data}else{const r=await supabase.from('ebooks').update({title:name.trim(),source_file_path:path,source_type:type}).eq('id',e.id).select().single();if(r.error)throw r.error;e=r.data}setEbook(e);setStep(1);await loadProjects();setNotice('✓ Conteúdo salvo.')}catch(err){setNotice(`Erro: ${err.message}`)}finally{setBusy(false)}};
 const saveStyle=async()=>{if(!project)return;setBusy(true);const r=await supabase.from('projects').update({language,current_step:2,style_notes:JSON.stringify({audience,visualStyle})}).eq('id',project.id).select().single();setBusy(false);if(r.error)return setNotice(`Erro: ${r.error.message}`);setProject(r.data);setStep(2);setNotice('✓ Estilo salvo.')};
 const uploadAsset=async(type,img)=>{if(!img||!project||!ebook)return;setBusy(true);try{const path=`${session.user.id}/${project.id}/${type}/${Date.now()}-${clean(img.name)}`;const u=await supabase.storage.from('ebook-assets').upload(path,img,{contentType:img.type||'image/png'});if(u.error)throw u.error;const r=await supabase.from('assets').insert({project_id:project.id,ebook_id:ebook.id,asset_type:type,file_path:path,mime_type:img.type,generation_prompt:assetPrompt||null,source:'upload'});if(r.error)throw r.error;await loadAssets(project.id);setNotice('✓ Imagem salva.')}catch(err){setNotice(`Erro: ${err.message}`)}finally{setBusy(false)}};
 const removeAsset=async a=>{await supabase.storage.from('ebook-assets').remove([a.file_path]);await supabase.from('assets').delete().eq('id',a.id);await loadAssets(project.id)};
 const signedSource=async()=>{const r=await supabase.storage.from('ebook-sources').createSignedUrl(ebook.source_file_path,300);if(r.error)throw r.error;return r.data.signedUrl};
 const extractSource=async()=>{const url=await signedSource();const response=await fetch(url);const buffer=await response.arrayBuffer();if((ebook.source_type||'').toLowerCase()==='pdf'){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const doc=await pdfjs.getDocument({data:new Uint8Array(buffer),disableWorker:true}).promise;const out=[];for(let i=1;i<=doc.numPages;i++){const page=await doc.getPage(i),tc=await page.getTextContent();out.push(tc.items.map(x=>x.str).join(' ').replace(/\s+/g,' ').trim())}return out}const mammoth=await import('mammoth/mammoth.browser');const result=await mammoth.extractRawText({arrayBuffer:buffer});return chunkText(result.value)};
 const buildEbook=async()=>{if(!ebook)return setNotice('Salve o conteúdo primeiro.');setBusy(true);setNotice('Lendo o arquivo e montando as páginas...');try{const texts=await extractSource();const cover=assets.find(a=>a.asset_type==='cover'),back=assets.find(a=>a.asset_type==='back_cover'),internal=assets.filter(a=>a.asset_type==='internal');await supabase.from('pages').delete().eq('ebook_id',ebook.id);const rows=[];let n=1;if(cover)rows.push({ebook_id:ebook.id,page_number:n++,page_type:'cover',title:name,body_text:'',layout_template:'full_image',image_asset_id:cover.id,sort_order:0});texts.forEach((t,i)=>rows.push({ebook_id:ebook.id,page_number:n++,page_type:'content',title:`Página ${i+1}`,body_text:t,layout_template:i%3===0?'image_top':i%3===1?'image_side':'text_focus',image_asset_id:internal.length?internal[i%internal.length].id:null,sort_order:i+1}));if(back)rows.push({ebook_id:ebook.id,page_number:n++,page_type:'back_cover',title:'Contracapa',body_text:'',layout_template:'full_image',image_asset_id:back.id,sort_order:rows.length});const ins=await supabase.from('pages').insert(rows).select();if(ins.error)throw ins.error;await supabase.from('ebooks').update({page_count:rows.length,content_status:'diagrammed'}).eq('id',ebook.id);await supabase.from('projects').update({current_step:3}).eq('id',project.id);setPages(ins.data||[]);setSelectedPage(ins.data?.[0]||null);setNotice(`✓ E-book montado com ${rows.length} páginas.`)}catch(err){setNotice(`Erro ao diagramar: ${err.message}`)}finally{setBusy(false)}};
 const savePage=async patch=>{if(!selectedPage)return;const next={...selectedPage,...patch};setSelectedPage(next);setPages(ps=>ps.map(p=>p.id===next.id?next:p));await supabase.from('pages').update(patch).eq('id',next.id)};
 const finishDiagram=async()=>{if(!pages.length)return setNotice('Monte o e-book primeiro.');await supabase.from('projects').update({current_step:4}).eq('id',project.id);setStep(4);setNotice('✓ Diagramação salva. Agora revise página por página.')};
 const previewImage=p=>{const a=assets.find(x=>x.id===p?.image_asset_id);return a?assetUrls[a.id]:null};
 if(view==='dashboard')return <div className="dashboardShell"><header className="dashboardHeader"><div className="brand dark"><div className="logo">E</div><div><strong>Ebook Studio IA</strong><span>Low Ticket Creator</span></div></div><button className="iconBtn" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/></button></header><main className="dashboardMain"><div className="dashboardTitle"><div><small>SEUS PROJETOS</small><h1>Meus e-books</h1><p>Abra um projeto ou crie um novo.</p></div><button className="primary" onClick={reset}><Plus size={18}/> NOVO E-BOOK</button></div>{loadingProjects?<div className="emptyState">Carregando...</div>:projects.length===0?<div className="emptyState"><FolderOpen size={42}/><h2>Nenhum e-book ainda</h2><button className="primary" onClick={reset}>CRIAR PRIMEIRO E-BOOK</button></div>:<div className="projectGrid">{projects.map(item=>{const e=item.ebooks?.[0],current=steps[Math.max(0,Math.min(5,item.current_step||0))][0];return <button className="projectCard" key={item.id} onClick={()=>open(item)}><div className="projectIcon"><BookOpen size={23}/></div><div className="projectCardBody"><span className="statusPill">Etapa: {current}</span><h3>{item.name}</h3><p>{e?.source_type?e.source_type.toUpperCase():'Sem arquivo'} · {item.format?.replace('_',' ')}</p><small><Clock3 size={13}/> {date(item.updated_at)}</small></div><span className="openLabel">ABRIR →</span></button>})}</div>}</main></div>;
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">E</div><div><strong>Ebook Studio IA</strong><span>Low Ticket Creator</span></div></div><button className="backDash" onClick={async()=>{await loadProjects();setView('dashboard')}}><ArrowLeft size={17}/> Meus e-books</button><nav>{steps.map(([l,I],i)=><button key={l} className={step===i?'active':''} onClick={()=>goto(i)}><span className="stepNumber">{i+1}</span><I size={18}/>{l}</button>)}</nav><div className="connection"><i></i> Supabase conectado</div></aside><main><header><div><small>PROJETO ATUAL</small><h1>{project?.name||title}</h1></div><div className="headerActions"><button className="secondary" onClick={reset}><Plus size={17}/> Novo e-book</button><button className="iconBtn" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/></button></div></header>
 {step===0&&<section><div className="hero"><div><span className="tag">PASSO 1</span><h2>Envie o conteúdo revisado</h2><p>PDF ou DOCX.</p></div><label className="upload"><Upload size={32}/><strong>{file?file.name:ebook?.source_type?`Arquivo ${ebook.source_type.toUpperCase()} salvo`:'Selecionar e-book'}</strong><input type="file" accept=".pdf,.doc,.docx" onChange={e=>{const f=e.target.files?.[0];if(f){setFile(f);if(!name)setName(f.name.replace(/\.[^/.]+$/,''))}}}/></label></div><div className="fields"><label>Nome<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Formato<select value={format} onChange={e=>setFormat(e.target.value)}><option value="A5_vertical">A5 Vertical</option><option value="A4_vertical">A4 Vertical</option><option value="square">Quadrado 1:1</option><option value="mobile">Mobile</option></select></label></div><div className="actionRow"><button className="primary" onClick={saveContent} disabled={busy}><Save size={17}/>SALVAR E CONTINUAR</button></div></section>}
 {step===1&&<section><div className="sectionTitle"><span className="tag">PASSO 2</span><h2>Identidade visual</h2></div><div className="fields three"><label>Público<select value={audience} onChange={e=>setAudience(e.target.value)}><option>Infantil</option><option>Adulto</option><option>Família</option></select></label><label>Estilo<select value={visualStyle} onChange={e=>setVisualStyle(e.target.value)}><option>3D Premium</option><option>Minimalista Premium</option><option>Editorial</option></select></label><label>Idioma<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="pt-BR">Português</option><option value="es">Espanhol</option><option value="en">Inglês</option></select></label></div><div className="actionRow"><button className="primary" onClick={saveStyle}>SALVAR ESTILO E CONTINUAR</button></div></section>}
 {step===2&&<section><div className="sectionTitle"><span className="tag">PASSO 3</span><h2>Imagens do projeto</h2><p>Envie capa, contracapa, ilustrações e mockup. Os arquivos ficam privados.</p></div><label>Briefing visual<textarea className="promptBox" value={assetPrompt} onChange={e=>setAssetPrompt(e.target.value)} placeholder="Ex.: ilustração 3D premium, luz cinematográfica..."/></label><div className="assetGrid">{assetTypes.map(([k,l])=><label className="asset" key={k}><b>{l}</b><p>PNG, JPG ou WebP</p><span>ADICIONAR →</span><input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadAsset(k,e.target.files?.[0])}/></label>)}</div><div className="assetLibrary">{assets.map(a=><div className="assetThumb" key={a.id}>{assetUrls[a.id]?<img src={assetUrls[a.id]}/>:<div>Imagem</div>}<small>{assetTypes.find(x=>x[0]===a.asset_type)?.[1]||a.asset_type}</small><button onClick={()=>removeAsset(a)}><Trash2 size={14}/></button></div>)}</div><div className="actionRow"><button className="primary" onClick={()=>goto(3)} disabled={!assets.length}>CONTINUAR PARA DIAGRAMAÇÃO</button></div></section>}
 {step===3&&<section><div className="sectionTitle"><span className="tag">PASSO 4</span><h2>Diagramação automática</h2><p>O app lê o PDF/DOCX, cria as páginas, distribui suas imagens e salva tudo no Supabase.</p></div><div className="diagramToolbar"><button className="primary" onClick={buildEbook} disabled={busy}>{busy?'MONTANDO...':'MONTAR EBOOK COMPLETO'}</button><span>{pages.length?`${pages.length} páginas montadas`:'Ainda não montado'}</span></div>{pages.length>0&&<div className="diagramWorkspace"><div className="pageList">{pages.map(p=><button key={p.id} className={selectedPage?.id===p.id?'selected':''} onClick={()=>setSelectedPage(p)}><b>{p.page_number}</b><span>{p.page_type==='cover'?'Capa':p.page_type==='back_cover'?'Contracapa':p.title}</span></button>)}</div><div className={`pagePreview ${selectedPage?.layout_template||''}`}>{previewImage(selectedPage)&&<img src={previewImage(selectedPage)}/>}<div className="pageText"><h3>{selectedPage?.title}</h3><p>{selectedPage?.body_text}</p></div></div><div className="pageInspector"><h3>Ajustes da página</h3><label>Layout<select value={selectedPage?.layout_template||'text_focus'} onChange={e=>savePage({layout_template:e.target.value})}><option value="text_focus">Texto principal</option><option value="image_top">Imagem no topo</option><option value="image_side">Imagem lateral</option><option value="full_image">Imagem total</option></select></label><label>Imagem<select value={selectedPage?.image_asset_id||''} onChange={e=>savePage({image_asset_id:e.target.value||null})}><option value="">Sem imagem</option>{assets.filter(a=>['cover','back_cover','internal'].includes(a.asset_type)).map(a=><option value={a.id} key={a.id}>{assetTypes.find(x=>x[0]===a.asset_type)?.[1]}</option>)}</select></label><label>Título<input value={selectedPage?.title||''} onChange={e=>savePage({title:e.target.value})}/></label><label>Texto<textarea className="bodyEditor" value={selectedPage?.body_text||''} onChange={e=>savePage({body_text:e.target.value})}/></label></div></div>}<div className="actionRow"><button className="primary" onClick={finishDiagram} disabled={!pages.length}>SALVAR DIAGRAMAÇÃO E REVISAR</button></div></section>}
 {step===4&&<section><div className="sectionTitle"><span className="tag">PASSO 5</span><h2>Revisão visual</h2><p>Confira as páginas montadas antes da exportação.</p></div><div className="reviewCards">{pages.map(p=><button key={p.id} onClick={()=>{setSelectedPage(p);setStep(3)}}><b>Página {p.page_number}</b><span>{p.page_type}</span></button>)}</div><div className="actionRow"><button className="primary" onClick={()=>goto(5)}>APROVAR E IR PARA EXPORTAÇÃO</button></div></section>}
 {step===5&&<section><div className="sectionTitle"><span className="tag">PASSO 6</span><h2>Exportar</h2><p>A estrutura final já está salva. A geração física dos PDFs/PNGs será conectada na próxima etapa.</p></div><div className="exportGrid">{['PDF Digital','PDF para Impressão','Capa PNG','Mockup PNG'].map(x=><button key={x}><strong>{x}</strong><span>Preparar arquivo final</span></button>)}</div></section>}
 {notice&&<div className={notice.startsWith('Erro')?'error':'notice'}>{notice}</div>}
 </main></div>
}
